### ISSUE TITLE
Build fails on Windows 11: symlink.canonicalize failed

### ISSUE THREAD

**Issue by Boscop** [rscarson/rustyscript#221]
It fails to build for me on Windows 11. Any idea why the symblink failed to be created? 🙂

```
error: failed to run custom build command for `v8 v0.99.0`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_DEV_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `D:\dev\3rdparty\rustyscript\target\debug\build\v8-15127174e74c0e93\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-changed=.gn
  cargo:rerun-if-changed=BUILD.gn
  cargo:rerun-if-changed=src/binding.cc
  cargo:rerun-if-env-changed=CCACHE
  cargo:rerun-if-env-changed=CLANG_BASE_PATH
  cargo:rerun-if-env-changed=CXXSTDLIB
  cargo:rerun-if-env-changed=DENO_TRYBUILD
  cargo:rerun-if-env-changed=DOCS_RS
  cargo:rerun-if-env-changed=GN
  cargo:rerun-if-env-changed=GN_ARGS
  cargo:rerun-if-env-changed=HOST
  cargo:rerun-if-env-changed=NINJA
  cargo:rerun-if-env-changed=OUT_DIR
  cargo:rerun-if-env-changed=RUSTY_V8_ARCHIVE
  cargo:rerun-if-env-changed=RUSTY_V8_MIRROR
  cargo:rerun-if-env-changed=SCCACHE
  cargo:rerun-if-env-changed=V8_FORCE_DEBUG
  cargo:rerun-if-env-changed=V8_FROM_SOURCE
  cargo:rerun-if-env-changed=PYTHON
  cargo:rerun-if-env-changed=DISABLE_CLANG
  cargo:rerun-if-env-changed=EXTRA_GN_ARGS
  cargo:rerun-if-env-changed=NO_PRINT_GN_ARGS
  cargo:rerun-if-env-changed=CARGO_ENCODED_RUSTFLAGS
  cargo:rustc-link-lib=static=rusty_v8
  cargo:rustc-link-lib=dylib=winmm
  cargo:rustc-link-lib=dylib=dbghelp
  cargo:rustc-link-lib=dylib=msvcprt
  lockfile: "D:\\dev\\3rdparty\\rustyscript\\target\\debug\\build\\v8.fslock"
  Creating symlink "D:\\dev\\3rdparty\\rustyscript\\target\\debug\\gn_root" to "C:\\Users\\me\\scoop\\persist\\rustup\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\v8-0.99.0"       
  symlink.canonicalize failed: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }
  symlink_dir failed: Os { code: 1314, kind: Uncategorized, message: "A required privilege is not held by the client." }
  symlink.canonicalize failed: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }
  symlink_dir failed: Os { code: 1314, kind: Uncategorized, message: "A required privilege is not held by the client." }
  symlink.canonicalize failed: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }
  symlink_dir failed: Os { code: 1314, kind: Uncategorized, message: "A required privilege is not held by the client." }
  symlink.canonicalize failed: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }
  symlink_dir failed: Os { code: 1314, kind: Uncategorized, message: "A required privilege is not held by the client." }
  symlink.canonicalize failed: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }
  symlink_dir failed: Os { code: 1314, kind: Uncategorized, message: "A required privilege is not held by the client." }

  --- stderr
  remove_dir_all failed: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }
  remove_file failed: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }
  remove_dir_all failed: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }
  remove_file failed: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }
  remove_dir_all failed: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }
  remove_file failed: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }
  remove_dir_all failed: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }
  remove_file failed: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }
  remove_dir_all failed: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }
  remove_file failed: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }
  thread 'main' panicked at C:\Users\me\scoop\persist\rustup\.cargo\registry\src\index.crates.io-6f17d22bba15001f\v8-0.99.0\build.rs:871:17:
  Failed to create symlink
  stack backtrace:
     0:     0x7ff75b98b4f4 - std::backtrace_rs::backtrace::dbghelp64::trace
                                 at /rustc/8b3870784f69d8ed2ae4246d1b56f150e3131499\library/std\src\..\..\backtrace\src\backtrace\dbghelp64.rs:91
     1:     0x7ff75b98b4f4 - std::backtrace_rs::backtrace::trace_unsynchronized
                                 at /rustc/8b3870784f69d8ed2ae4246d1b56f150e3131499\library/std\src\..\..\backtrace\src\backtrace\mod.rs:66
     2:     0x7ff75b98b4f4 - std::sys::backtrace::_print_fmt
                                 at /rustc/8b3870784f69d8ed2ae4246d1b56f150e3131499\library/std\src\sys\backtrace.rs:66
     3:     0x7ff75b98b4f4 - std::sys::backtrace::impl$0::print::impl$0::fmt
                                 at /rustc/8b3870784f69d8ed2ae4246d1b56f150e3131499\library/std\src\sys\backtrace.rs:39
     4:     0x7ff75b9ad269 - core::fmt::rt::Argument::fmt
                                 at /rustc/8b3870784f69d8ed2ae4246d1b56f150e3131499\library/core\src\fmt\rt.rs:173
     5:     0x7ff75b9ad269 - core::fmt::write
                                 at /rustc/8b3870784f69d8ed2ae4246d1b56f150e3131499\library/core\src\fmt\mod.rs:1178
     6:     0x7ff75b9869a7 - std::io::Write::write_fmt<std::sys::pal::windows::stdio::Stderr>
                                 at /rustc/8b3870784f69d8ed2ae4246d1b56f150e3131499\library/std\src\io\mod.rs:1823
     7:     0x7ff75b98d8c9 - std::panicking::default_hook::closure$1
                                 at /rustc/8b3870784f69d8ed2ae4246d1b56f150e3131499\library/std\src\panicking.rs:266
     8:     0x7ff75b98d44c - std::panicking::default_hook
                                 at /rustc/8b3870784f69d8ed2ae4246d1b56f150e3131499\library/std\src\panicking.rs:293
     9:     0x7ff75b98e1d2 - std::panicking::rust_panic_with_hook
                                 at /rustc/8b3870784f69d8ed2ae4246d1b56f150e3131499\library/std\src\panicking.rs:797
    10:     0x7ff75b98dfdf - std::panicking::begin_panic_handler::closure$0
                                 at /rustc/8b3870784f69d8ed2ae4246d1b56f150e3131499\library/std\src\panicking.rs:664
    11:     0x7ff75b98bfaf - std::sys::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
                                 at /rustc/8b3870784f69d8ed2ae4246d1b56f150e3131499\library/std\src\sys\backtrace.rs:170
    12:     0x7ff75b98dc26 - std::panicking::begin_panic_handler
                                 at /rustc/8b3870784f69d8ed2ae4246d1b56f150e3131499\library/std\src\panicking.rs:662
    13:     0x7ff75b9b6554 - core::panicking::panic_fmt
                                 at /rustc/8b3870784f69d8ed2ae4246d1b56f150e3131499\library/core\src\panicking.rs:74
    14:     0x7ff75b291eae - build_script_build::not_in_depot_tools::hec5d5d7b164c0ee7
    15:     0x7ff75b29140e - build_script_build::not_in_depot_tools::hec5d5d7b164c0ee7
    16:     0x7ff75b290193 - build_script_build::print_link_flags::{{closure}}::{{closure}}::h7de7765f56705eae
    17:     0x7ff75b287f86 - <alloc::string::String as core::iter::traits::collect::FromIterator<char>>::from_iter::h3dbbf83300898818
    18:     0x7ff75b298966 - core::ops::function::FnOnce::call_once::h26e7191cdc6b6e69
    19:     0x7ff75b282189 - std::rt::lang_start::{{closure}}::he2f2b69a23810b7c
    20:     0x7ff75b28212c - std::rt::lang_start::{{closure}}::he2f2b69a23810b7c
    21:     0x7ff75b9814b9 - std::rt::lang_start_internal::closure$2
                                 at /rustc/8b3870784f69d8ed2ae4246d1b56f150e3131499\library/std\src\rt.rs:143
    22:     0x7ff75b9814b9 - std::panicking::try::do_call
                                 at /rustc/8b3870784f69d8ed2ae4246d1b56f150e3131499\library/std\src\panicking.rs:554
    23:     0x7ff75b9814b9 - std::panicking::try
                                 at /rustc/8b3870784f69d8ed2ae4246d1b56f150e3131499\library/std\src\panicking.rs:518
    24:     0x7ff75b9814b9 - std::panic::catch_unwind
                                 at /rustc/8b3870784f69d8ed2ae4246d1b56f150e3131499\library/std\src\panic.rs:345
    25:     0x7ff75b9814b9 - std::rt::lang_start_internal
                                 at /rustc/8b3870784f69d8ed2ae4246d1b56f150e3131499\library/std\src\rt.rs:143
    26:     0x7ff75b282107 - std::rt::lang_start::hdf0d2608c75f470b
    27:     0x7ff75b2949b9 - main
    28:     0x7ff75b9b3870 - invoke_main
                                 at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
    29:     0x7ff75b9b3870 - __scrt_common_main_seh
                                 at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
    30:     0x7fff35ac257d - BaseThreadInitThunk
    31:     0x7fff37baaf28 - RtlUserThreadStart
warning: build failed, waiting for other jobs to finish...
```

If fails in `C:\Users\me\scoop\persist\rustup\.cargo\registry\src\index.crates.io-6f17d22bba15001f\v8-0.99.0\build.rs` in this function:
```rs
#[cfg(target_os = "windows")]
fn maybe_symlink_root_dir(dirs: &mut Dirs) {
  // GN produces invalid paths if the source (a.k.a. root) directory is on a
  // different drive than the output. If this is the case we'll create a
  // symlink called 'gn_root' in the out directory, next to 'gn_out', so it
  // appears as if they're both on the same drive.
  use std::fs::remove_dir_all;
  use std::fs::remove_file;
  use std::os::windows::fs::symlink_dir;

  let get_prefix = |p: &Path| {
    p.components()
      .find_map(|c| match c {
        std::path::Component::Prefix(p) => Some(p),
        _ => None,
      })
      .map(|p| p.as_os_str().to_owned())
  };

  let Dirs { out, root } = dirs;
  if get_prefix(out) != get_prefix(root) {
    let symlink = &*out.join("gn_root");
    let target = &*root.canonicalize().unwrap();

    println!("Creating symlink {:?} to {:?}", &symlink, &root);

    let mut retries = 0;
    loop {
      match symlink.canonicalize() {
        Ok(existing) if existing == target => break,
        Ok(_) => remove_dir_all(symlink).expect("remove_dir_all failed"),
        Err(err) => {
          println!("symlink.canonicalize failed: {:?}", err);
          // we're having very strange issues on GHA when the cache
          // is restored, so trying this out temporarily
          if let Err(err) = remove_dir_all(symlink) {
            eprintln!("remove_dir_all failed: {:?}", err);
            if let Err(err) = remove_file(symlink) {
              eprintln!("remove_file failed: {:?}", err);
            }
          }
          match symlink_dir(target, symlink) {
            Ok(_) => break,
            Err(err) => {
              println!("symlink_dir failed: {:?}", err);
              retries += 1;
              std::thread::sleep(std::time::Duration::from_millis(
                50 * retries,
              ));
              if retries > 4 {
                panic!("Failed to create symlink");
              }
            }
          }
        }
      }
    }

    dirs.root = symlink.to_path_buf();
  }
}
```

**Comment by Boscop** [comment]
Ah, this is the issue: https://github.com/denoland/rusty_v8/issues/1563
I turned on developer mode and now it compiles :)
