### ISSUE TITLE
when has console.log , ModuleWrapper will crash

### ISSUE THREAD

**Issue by i18n-now** [rscarson/rustyscript#85]
<img width="1728" alt="image" src="https://github.com/rscarson/rustyscript/assets/145643935/2fbb6ae2-1293-4570-92d7-27388ffe4789">

```
Error: Error: Bad resource ID
    at Object.print (ext:core/01_core.js:817:32)
    at Console.<anonymous> (ext:init_console/init_console.js:6:64)
    at console.log (ext:deno_console/01_console.js:3155:20)
    at file:///Users/z/i18n/testx/test.js:2:13

Stack backtrace:
   0: std::backtrace_rs::backtrace::libunwind::trace
             at /rustc/f705de59625bb76067a5d102edc1575ff23b8845/library/std/src/../../backtrace/src/backtrace/libunwind.rs:105:5
   1: std::backtrace_rs::backtrace::trace_unsynchronized
             at /rustc/f705de59625bb76067a5d102edc1575ff23b8845/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2: std::backtrace::Backtrace::create
             at /rustc/f705de59625bb76067a5d102edc1575ff23b8845/library/std/src/backtrace.rs:331:13
   3: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from
             at /Users/z/.cargo/registry/src/index.crates.io-6f17d22bba15001f/anyhow-1.0.82/src/backtrace.rs:27:14
   4: <core::result::Result<T,F> as core::ops::try_trait::FromResidual<core::result::Result<core::convert::Infallible,E>>>::from_residual
             at /rustc/f705de59625bb76067a5d102edc1575ff23b8845/library/core/src/result.rs:1964:27
   5: tjs::main
             at ./src/main.rs:29:9
   6: core::ops::function::FnOnce::call_once
             at /rustc/f705de59625bb76067a5d102edc1575ff23b8845/library/core/src/ops/function.rs:250:5
   7: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/f705de59625bb76067a5d102edc1575ff23b8845/library/std/src/sys_common/backtrace.rs:155:18
   8: std::rt::lang_start::{{closure}}
             at /rustc/f705de59625bb76067a5d102edc1575ff23b8845/library/std/src/rt.rs:159:18
   9: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/f705de59625bb76067a5d102edc1575ff23b8845/library/core/src/ops/function.rs:284:13
  10: std::panicking::try::do_call
             at /rustc/f705de59625bb76067a5d102edc1575ff23b8845/library/std/src/panicking.rs:559:40
  11: std::panicking::try
             at /rustc/f705de59625bb76067a5d102edc1575ff23b8845/library/std/src/panicking.rs:523:19
  12: std::panic::catch_unwind
             at /rustc/f705de59625bb76067a5d102edc1575ff23b8845/library/std/src/panic.rs:149:14
  13: std::rt::lang_start_internal::{{closure}}
             at /rustc/f705de59625bb76067a5d102edc1575ff23b8845/library/std/src/rt.rs:141:48
  14: std::panicking::try::do_call
             at /rustc/f705de59625bb76067a5d102edc1575ff23b8845/library/std/src/panicking.rs:559:40
  15: std::panicking::try
             at /rustc/f705de59625bb76067a5d102edc1575ff23b8845/library/std/src/panicking.rs:523:19
  16: std::panic::catch_unwind
             at /rustc/f705de59625bb76067a5d102edc1575ff23b8845/library/std/src/panic.rs:149:14
  17: std::rt::lang_start_internal
             at /rustc/f705de59625bb76067a5d102edc1575ff23b8845/library/std/src/rt.rs:141:20
  18: std::rt::lang_start
```

**Comment by rscarson** [comment]
I will try to reproduce this

**Comment by i18n-now** [comment]
https://github.com/i18n-site/ejs/blob/main/src/main.rs
code here

**Comment by rscarson** [comment]
Please try updating to 0.4.0 and see if the error still occurs

**Comment by i18n-now** [comment]
the console.log is ok 


but I got a new error ( code is there https://github.com/i18n-site/ejs )

I don't know how to resolve this error

```
   Compiling ejs v0.1.2 (/Users/z/i18n/ejs)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.72s
     Running `/tmp/rust/target/debug/ejs`
thread 'main' panicked at /Users/z/.cargo/registry/src/index.crates.io-6f17d22bba15001f/deno_core-0.278.0/runtime/jsruntime.rs:619:9:
Failed to initialize a JsRuntime: Uncaught SyntaxError: The requested module 'ext:core/ops' does not provide an export named 'op_set_raw'
    at ext:deno_io/12_io.js:8:10

Stack backtrace:
   0: std::backtrace_rs::backtrace::libunwind::trace
             at /rustc/f705de59625bb76067a5d102edc1575ff23b8845/library/std/src/../../backtrace/src/backtrace/libunwind.rs:105:5
   1: std::backtrace_rs::backtrace::trace_unsynchronized
             at /rustc/f705de59625bb76067a5d102edc1575ff23b8845/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2: std::backtrace::Backtrace::create
             at /rustc/f705de59625bb76067a5d102edc1575ff23b8845/library/std/src/backtrace.rs:331:13
   3: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from
             at /Users/z/.cargo/registry/src/index.crates.io-6f17d22bba15001f/anyhow-1.0.82/src/backtrace.rs:27:14
   4: <T as core::convert::Into<U>>::into
             at /rustc/f705de59625bb76067a5d102edc1575ff23b8845/library/core/src/convert/mod.rs:759:9
   5: deno_core::error::exception_to_err_result
             at /Users/z/.cargo/registry/src/index.crates.io-6f17d22bba15001f/deno_core-0.278.0/error.rs:731:7
   6: deno_core::runtime::jsrealm::JsRealm::load_side_es_module_from_code::{{closure}}::{{closure}}
             at /Users/z/.cargo/registry/src/index.crates.io-6f17d22bba15001f/deno_core-0.278.0/runtime/jsrealm.rs:417:7
   7: core::result::Result<T,E>::map_err
             at /rustc/f705de59625bb76067a5d102edc1575ff23b8845/library/core/src/result.rs:829:27
   8: deno_core::runtime::jsrealm::JsRealm::load_side_es_module_from_code::{{closure}}
             at /Users/z/.cargo/registry/src/index.crates.io-6f17d22bba15001f/deno_core-0.278.0/runtime/jsrealm.rs:415:5
   9: deno_core::runtime::jsruntime::JsRuntime::init_extension_js_inner::{{closure}}
             at /Users/z/.cargo/registry/src/index.crates.io-6f17d22bba15001f/deno_core-0.278.0/runtime/jsruntime.rs:1169:10
  10: futures_executor::local_pool::block_on::{{closure}}
             at /Users/z/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-executor-0.3.30/src/local_pool.rs:317:23
  11: futures_executor::local_pool::run_executor::{{closure}}
             at /Users/z/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-executor-0.3.30/src/local_pool.rs:90:37
  12: std::thread::local::LocalKey<T>::try_with
             at /rustc/f705de59625bb76067a5d102edc1575ff23b8845/library/std/src/thread/local.rs:286:12
  13: std::thread::local::LocalKey<T>::with
             at /rustc/f705de59625bb76067a5d102edc1575ff23b8845/library/std/src/thread/local.rs:262:9
  14: futures_executor::local_pool::run_executor
             at /Users/z/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-executor-0.3.30/src/local_pool.rs:86:5
  15: futures_executor::local_pool::block_on
             at /Users/z/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-executor-0.3.30/src/local_pool.rs:317:5
  16: deno_core::runtime::jsruntime::JsRuntime::init_extension_js
             at /Users/z/.cargo/registry/src/index.crates.io-6f17d22bba15001f/deno_core-0.278.0/runtime/jsruntime.rs:1213:5
  17: deno_core::runtime::jsruntime::JsRuntime::new_inner
             at /Users/z/.cargo/registry/src/index.crates.io-6f17d22bba15001f/deno_core-0.278.0/runtime/jsruntime.rs:980:7
  18: deno_core::runtime::jsruntime::JsRuntime::new
             at /Users/z/.cargo/registry/src/index.crates.io-6f17d22bba15001f/deno_core-0.278.0/runtime/jsruntime.rs:616:11
  19: rustyscript::inner_runtime::InnerRuntime::new
             at /Users/z/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustyscript-0.4.0/src/inner_runtime.rs:53:27
  20: rustyscript::runtime::Runtime::new
             at /Users/z/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustyscript-0.4.0/src/runtime.rs:57:17
  21: rustyscript::module_wrapper::ModuleWrapper::new_from_module
             at /Users/z/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustyscript-0.4.0/src/module_wrapper.rs:23:27
  22: rustyscript::module_wrapper::ModuleWrapper::new_from_file
             at /Users/z/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustyscript-0.4.0/src/module_wrapper.rs:43:9
  23: ejs::main
             at ./src/main.rs:13:20
  24: core::ops::function::FnOnce::call_once
             at /rustc/f705de59625bb76067a5d102edc1575ff23b8845/library/core/src/ops/function.rs:250:5
  25: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/f705de59625bb76067a5d102edc1575ff23b8845/library/std/src/sys_common/backtrace.rs:155:18
  26: std::rt::lang_start::{{closure}}
             at /rustc/f705de59625bb76067a5d102edc1575ff23b8845/library/std/src/rt.rs:159:18
  27: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/f705de59625bb76067a5d102edc1575ff23b8845/library/core/src/ops/function.rs:284:13
  28: std::panicking::try::do_call
             at /rustc/f705de59625bb76067a5d102edc1575ff23b8845/library/std/src/panicking.rs:559:40
  29: std::panicking::try
             at /rustc/f705de59625bb76067a5d102edc1575ff23b8845/library/std/src/panicking.rs:523:19
  30: std::panic::catch_unwind
             at /rustc/f705de59625bb76067a5d102edc1575ff23b8845/library/std/src/panic.rs:149:14
  31: std::rt::lang_start_internal::{{closure}}
             at /rustc/f705de59625bb76067a5d102edc1575ff23b8845/library/std/src/rt.rs:141:48
  32: std::panicking::try::do_call
             at /rustc/f705de59625bb76067a5d102edc1575ff23b8845/library/std/src/panicking.rs:559:40
  33: std::panicking::try
             at /rustc/f705de59625bb76067a5d102edc1575ff23b8845/library/std/src/panicking.rs:523:19
  34: std::panic::catch_unwind
             at /rustc/f705de59625bb76067a5d102edc1575ff23b8845/library/std/src/panic.rs:149:14
  35: std::rt::lang_start_internal
             at /rustc/f705de59625bb76067a5d102edc1575ff23b8845/library/std/src/rt.rs:141:20
  36: std::rt::lang_start
             at /rustc/f705de59625bb76067a5d102edc1575ff23b8845/library/std/src/rt.rs:158:17
  37: _main
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f705de59625bb76067a5d102edc1575ff23b8845/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_fmt
             at /rustc/f705de59625bb76067a5d102edc1575ff23b8845/library/core/src/panicking.rs:72:14
   2: deno_core::runtime::jsruntime::JsRuntime::new
             at /Users/z/.cargo/registry/src/index.crates.io-6f17d22bba15001f/deno_core-0.278.0/runtime/jsruntime.rs:619:9
   3: rustyscript::inner_runtime::InnerRuntime::new
             at /Users/z/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustyscript-0.4.0/src/inner_runtime.rs:53:27
   4: rustyscript::runtime::Runtime::new
             at /Users/z/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustyscript-0.4.0/src/runtime.rs:57:17
   5: rustyscript::module_wrapper::ModuleWrapper::new_from_module
             at /Users/z/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustyscript-0.4.0/src/module_wrapper.rs:23:27
   6: rustyscript::module_wrapper::ModuleWrapper::new_from_file
             at /Users/z/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustyscript-0.4.0/src/module_wrapper.rs:43:9
   7: ejs::main
             at ./src/main.rs:13:20
   8: core::ops::function::FnOnce::call_once
             at /rustc/f705de59625bb76067a5d102edc1575ff23b8845/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Command exited with 101]
```

**Comment by rscarson** [comment]
Looks like deno_io depends on `runtime/ops/tty.rs` from denoland/deno proper

You could implement the ops in there on your end for now and I'll integrate that extension as a rustyscript feature for the next version

**Comment by rscarson** [comment]
deno_io has been as a rustyscript feature
As of 0.4.2 you can simply enable the `io` feature instead
